apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookrental
  labels:
    app: bookrental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookrental
  template:
    metadata:
      labels:
        app: bookrental
    spec:
      containers:
        - name: bookrental
          image: jtkim2000acr.azurecr.io/bookrental:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5