apiVersion: apps/v1
kind: Deployment
metadata:
  name: warningletter
  labels:
    app: warningletter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warningletter
  template:
    metadata:
      labels:
        app: warningletter
    spec:
      containers:
        - name: warningletter
          image: jtkim2000acr.azurecr.io/warningletter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5