server:
  port: 8080
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: book
          destination: bookrental
          contentType: application/json
        event-out:
          destination: bookrental
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8082
---

spring:
  profiles: docker
  # datasource:
  #   driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #   url: jdbc:sqlserver://jtkimdbserver.database.windows.net:1433;database=bookrentaldb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  #   username: dbadmin
  #   password: jtkim2000!!
    #username: ${SQLSERVER_USERNAME}
    #password: ${SQLSERVER_PASSWORD}
  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:file:./customerdb
  #   username: customerUser
  #   password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: book
          destination: bookrental
          contentType: application/json
        event-out:
          destination: bookrental
          contentType: application/json
