apiVersion: apps/v1
kind: Deployment
metadata:
  name: reasonletter
  labels:
    app: reasonletter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reasonletter
  template:
    metadata:
      labels:
        app: reasonletter
    spec:
      containers:
        - name: reasonletter
          image: jtkim2000acr.azurecr.io/reasonletter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5