apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookrentalrequest
  labels:
    app: bookrentalrequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookrentalrequest
  template:
    metadata:
      labels:
        app: bookrentalrequest
    spec:
      containers:
        - name: bookrentalrequest
          image: jtkimacr.azurecr.io/bookrentalrequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: 300m
              ## memory: 256Mi
            limits:
              cpu: 500m
              ## memory: 256Mi
