apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bookrentalrequest-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bookrentalrequest
  targetCPUUtilizationPercentage: 50